baseURL = 'https://zac.events/'
languageCode = 'en-us'
title = "Zac's Summer Movie Night"
theme = 'papermod2'

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = false
[params]
    hideFooter = true
    [params.label]
        icon = '/moviebanner5.png'
        text = "Zac's Summer Movie Night"
    [params.assets]
        disableFingerprinting = true